# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.5.dev8+ga380339.d20230901'
__version_tuple__ = version_tuple = (0, 1, 5, 'dev8', 'ga380339.d20230901')
