name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@2.5.0
        env:
          # disable PyPy wheels, 32-bit
          CIBW_SKIP: "pp* *-win32 *-manylinux_i686"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
